AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Apache Web Server Parameters"
        Parameters:
          - EC2Name
          - EC2InstanceAMI
          - KeyName
          - InstanceType
          - Ec2SecurityGroup 
          - SubnetId
      - Label:
          default: "Security Group Parameters"
        Parameters:
          - SGName
          - SGDescription
    ParameterLabels:
      EC2Name:
        default: "Instance name"
      EC2InstanceAMI:
        default: "Apache AMI for Web Servers"  
      KeyName:
        default: "Key Pair for Web Server"  
      InstanceType:
        default: "Instance Type"  
      Ec2SecurityGroup:
        default: "Instance Security Group"
      SubnetId:
        default: "Subnet ID"
              
      SGName:
        default: "Security Group name"
      SGDescription:
        default: "Security Group description"
Parameters:
  EC2Name:
    Type: String
    Description: "A friendly name for our EC2 instance"
    Default: "apache-ec2"
  EC2InstanceAMI:
    Type: String
    Description: "This is the AMI used in Production"
    Default: "ami-03caa3f860895f82e"
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "This is the key"
    Default: test-keypair
  InstanceType: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
  Ec2SecurityGroup:
    Type: String
    Default: sg-0744fefce238b2852
    Description: Our Security Group
  SubnetId:
    Type: String
    Default: subnet-7f2ce419
    Description: Subnet ID
  SGName:
    Type: String
    Description: "A friendly name for our SG"
    Default: "apache-SG"
  SGDescription:
    Type: String
    Description: "A friendly description for our SG"
Resources:
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://skatz1990-stack.s3-us-west-1.amazonaws.com/ec2.yaml"
      Parameters:
        SubnetId: !Ref SubnetId
        ImageId: !Ref EC2InstanceAMI
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType
        SecurityGroupIds: !Ref Ec2SecurityGroup
  SG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://skatz1990-stack.s3-us-west-1.amazonaws.com/sg.yaml"
      Parameters:
        GroupDescription: !Ref SGDescription
        GroupName: !Ref SGName